Changing error responses in trasactions end poinds
omar5876/Skill-Up-JS-Backend pull request #12
Opened 2022-11-03 22:25 UTC by omar5876

## TICKET

- [INSERT TICKET NAME HERE](INSERT TICKET LINK HERE)

## Description
AS:
I Want:
To:

## Evidence:

![image](https://user-images.githubusercontent.com/90323455/199846035-a43313de-d257-4097-b53e-2a28392eeb5e.png)

2022-11-04 14:38 UTC, PJuanCruz approved these changes

2022-11-04 16:59 UTC, NachoAiup requested changes
podrias revisar el package-lock.json? creo que no deberia aparecer en el Pull Request, fijate si podes sacarlo asi no se mergea a development. Creo que es porque estas usando una version distinta de Node que no es la 14

2022-11-04 18:29 UTC, omar5876 commented
> podrias revisar el package-lock.json? creo que no deberia aparecer en el Pull Request, fijate si podes sacarlo asi no se mergea a development. Creo que es porque estas usando una version distinta de Node que no es la 14

ya lo borre, igual tengo la v14 de node

2022-11-04 20:06 UTC, NachoAiup commented
> > podrias revisar el package-lock.json? creo que no deberia aparecer en el Pull Request, fijate si podes sacarlo asi no se mergea a development. Creo que es porque estas usando una version distinta de Node que no es la 14
> 
> ya lo borre, igual tengo la v14 de node

si perdon, creo que el problema es que en el merge realizado de la branch [feat: add new user](https://github.com/omar5876/Skill-Up-JS-Backend/commit/06324e15401f003d355eec1fc15f666081e1fbc3) se modifico el package-lock.json a otra version. Habria que verificar cual de los dos archivos es el que tiene que quedar

2022-11-06 01:30 UTC, renatogastonruizgithub approved these changes

2022-11-08 12:32 UTC, NachoAiup approved these changes

2022-11-08 12:32 UTC, merged