Feat: Update Categories
omar5876/Skill-Up-JS-Backend pull request #13
Opened 2022-11-04 05:46 UTC by MaxiFerrioli

TICKET: #16

16. Endpoint para editar Categorias

2022-11-04 14:34 UTC, PJuanCruz approved these changes

2022-11-06 00:00 UTC, renatogastonruizgithub requested changes
fix resolved id not found and endpointResponse

2022-11-06 23:49 UTC, NachoAiup approved these changes

2022-11-06 23:58 UTC, MaxiFerrioli reviewed
Perfecto!

2022-11-07 13:46 UTC, merged