Middleware jwt
omar5876/Skill-Up-JS-Backend pull request #16
Opened 2022-11-04 15:02 UTC by renatogastonruizgithub

## TICKET

-22. Middleware de JWT

## Description
AS:
I Want:
To:

## Evidence:

### Happy Path
(Put screenshots/video/gifs here)

### Unhappy Path
(Put screenshots/video/gifs here)

2022-11-04 15:03 UTC, PJuanCruz approved these changes

2022-11-04 15:49 UTC, PJuanCruz requested changes
El middleware no debería responder nada en caso de éxito. La respuesta la tiene que hacer el controller.

2022-11-04 15:49 UTC, PJuanCruz commented on middlewares/authJwt.js
> +      res.status(200).json({
El middleware no debería responder nada en caso de éxito. La respuesta la tiene que hacer el controller.
Se podría guardar los datos decodificados en la request y pasar al controller. Algo así:
req.user = decoded;
next();

2022-11-05 14:49 UTC, NachoAiup approved these changes

2022-11-07 13:16 UTC, PJuanCruz approved these changes

2022-11-07 13:24 UTC, merged